version: '3.8'

services:
  frontend:
    build: ./byte-books-frontend
    ports:
      - '3000:3000'
    volumes:
      - ./byte-books-frontend/src:/app/src
    stdin_open: true
    tty: true

  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "8000:8000" 
    volumes:
      - ./backend:/app
    command: go run backend/cmd/*.go

  postgres:
    image: postgres:alpine
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "5432:5432" 
    volumes:
      - postgres-db:/app/database

volumes:
  postgres-db:
